"""empty message

Revision ID: 883eeda1cda5
Revises: 
Create Date: 2024-01-02 13:21:07.240412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883eeda1cda5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('training_status', sa.Enum('active', 'inactive', 'completed', name='training_status'), nullable=False),
    sa.Column('recall_duration_days', sa.Integer(), nullable=False),
    sa.Column('total_recall_count', sa.Integer(), nullable=False),
    sa.Column('perfect_recall_count', sa.Integer(), nullable=False),
    sa.Column('partial_recall_count', sa.Integer(), nullable=False),
    sa.Column('failed_recall_count', sa.Integer(), nullable=False),
    sa.Column('last_recall_outcome', sa.Enum('perfect', 'partial', 'failed', name='recall_outcome'), nullable=True),
    sa.Column('next_recall_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_recall_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memories')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
