name: Test Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Enable manual trigger
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:       
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11         
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      
      - name: Run tests
        run: pytest -v
